# Generated by Django 5.2.4 on 2025-09-11 13:44

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to=cms.models.banner_upload_path, verbose_name='Imagen')),
                ('link_url', models.URLField(blank=True, verbose_name='URL del botón')),
                ('link_label', models.CharField(blank=True, default='Ver más', max_length=40, verbose_name='Texto del botón')),
                ('position', models.CharField(choices=[('home_hero', 'Home — Hero (principal)'), ('home_strip', 'Home — Tira (debajo del hero)')], default='home_hero', max_length=40, verbose_name='Ubicación')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'order', '-updated_at'],
            },
        ),
    ]
