# Generated by Django 5.2.4 on 2025-10-08 16:03

import cms.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to=cms.models.banner_upload_path, verbose_name='Imagen')),
                ('link_url', models.URLField(blank=True, verbose_name='URL del botón')),
                ('link_label', models.CharField(blank=True, default='Ver más', max_length=40, verbose_name='Texto del botón')),
                ('position', models.CharField(choices=[('home_hero', 'Home — Hero (principal)'), ('home_strip', 'Home — Tira (debajo del hero)')], default='home_hero', max_length=40, verbose_name='Ubicación')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_width', models.PositiveIntegerField(default=1200, verbose_name='Ancho deseado (px)')),
                ('target_height', models.PositiveIntegerField(default=400, verbose_name='Alto deseado (px)')),
                ('fit_mode', models.CharField(choices=[('fill', 'Recortar para llenar (c_fill)'), ('fit', 'Ajustar sin recortar (c_fit)'), ('pad', 'Ajustar con bordes (c_pad)'), ('scale', 'Escalar (c_scale)')], default='fill', max_length=10, verbose_name='Modo de ajuste')),
            ],
            options={
                'ordering': ['position', 'order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Título')),
                ('url', models.CharField(help_text='Ej: /#categorias, /panel/, /categoria/12/', max_length=255, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Abrir en nueva pestaña')),
                ('staff_only', models.BooleanField(default=False, verbose_name='Solo staff')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem')),
            ],
            options={
                'verbose_name': 'Elemento de menú',
                'verbose_name_plural': 'Menú superior',
                'ordering': ['order', 'id'],
            },
        ),
    ]
