# Generated by Django 5.2.4 on 2025-09-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='fit_mode',
            field=models.CharField(choices=[('fill', 'Recortar para llenar (c_fill)'), ('fit', 'Ajustar sin recortar (c_fit)'), ('pad', 'Ajustar con bordes (c_pad)'), ('scale', 'Escalar (c_scale)')], default='fill', max_length=10, verbose_name='Modo de ajuste'),
        ),
        migrations.AddField(
            model_name='banner',
            name='target_height',
            field=models.PositiveIntegerField(default=400, verbose_name='Alto deseado (px)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='target_width',
            field=models.PositiveIntegerField(default=1200, verbose_name='Ancho deseado (px)'),
        ),
    ]
