# Generated by Django 5.2.4 on 2025-09-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_banner_fit_mode_banner_target_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Título')),
                ('url', models.CharField(help_text='Ej: /#categorias, /panel/, /categoria/12/', max_length=255, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Abrir en nueva pestaña')),
                ('staff_only', models.BooleanField(default=False, verbose_name='Solo staff')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem')),
            ],
            options={
                'verbose_name': 'Elemento de menú',
                'verbose_name_plural': 'Menú superior',
                'ordering': ['order', 'id'],
            },
        ),
    ]
