# Generated by Django 5.2.4 on 2025-10-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Artesanías Pachy', max_length=120, verbose_name='Nombre de marca')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='Logo (PNG/SVG/JPG)')),
                ('logo_width', models.PositiveIntegerField(default=140, verbose_name='Ancho del logo (px en navbar)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ajustes del sitio',
                'verbose_name_plural': 'Ajustes del sitio',
            },
        ),
    ]
