# Generated by Django 5.2.4 on 2025-09-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productimage_options_alter_productimage_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre interno')),
                ('code', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Código (cupón)')),
                ('dtype', models.CharField(choices=[('P', 'Porcentaje'), ('F', 'Monto fijo')], default='P', max_length=1, verbose_name='Tipo')),
                ('value', models.DecimalField(decimal_places=2, help_text='Si %: 10 = 10%; si fijo: 5000 = $5.000', max_digits=12, verbose_name='Valor')),
                ('scope', models.CharField(choices=[('ALL', 'Todos los productos'), ('PROD', 'Un producto'), ('CAT', 'Una categoría')], default='ALL', max_length=4, verbose_name='Ámbito')),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mínimo compra')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Desde')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Hasta')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Límite de usos')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Usos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('stackable', models.BooleanField(default=False, verbose_name='Acumulable')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
