# Generated by Django 5.2.4 on 2025-12-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='Anonimo', max_length=120),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
